
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 11 15:09:19 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int LBRACE = 11;
  public static final int INTEGER = 15;
  public static final int IN = 14;
  public static final int MOD = 8;
  public static final int VARIABLE = 16;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int DIV = 7;
  public static final int COMMA = 12;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int LET = 10;
  public static final int MUL = 6;
  public static final int RBRACE = 13;
  public static final int LPAREN = 2;
}

